spring.application.name=BatteryPack_Backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/supercaps_db
spring.datasource.username=supercaps_user
spring.datasource.password=iheb98285907


app.jwt.secret=change-this-to-a-long-random-secret-key-change-this-to-a-long-random-secret-key
app.jwt.expiration-ms=86400000
app.frontend-base-url=http://localhost:4200
app.mail.mode=${APP_MAIL_MODE:log}
app.mail.from=${APP_MAIL_FROM:no-reply@battery-platform.local}
spring.jpa.properties.hibernate.default_schema=app
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${MAIL_SMTP_TIMEOUT:5000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_SMTP_WRITE_TIMEOUT:5000}

mqtt.broker=tcp://10.0.30.14:1883
#mqtt.broker=tcp://192.168.33.10:1883

mqtt.client-id=supercaps-backend
mqtt.topic.lfp=packs/lfp/telemetry
mqtt.topic.supercap=packs/supercap/telemetry

#mqtt.username=
#mqtt.password=
